# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  timeout: 5000
  username: katsu
  password: 5Bs9Cd
  socket: /tmp/mysql.sock
  # host: localhost

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dating_development
  pool: 5
  username: katsu
  password: 5Bs9Cd
  # host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dating_test
  pool: 5
  username: katsu
  password: 5Bs9Cd
  # host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: heroku_442940a47d4fa8b
  pool: 5
  username: bd390abe2264a8
  password: <%= ENV['DB_PASSWORD'] %>
  host: http://us-cdbr-iron-east-03.cleardb.net
